### ISSUE TITLE
Update Spacing Scale

### ISSUE THREAD

**Issue by Anay-v2** [swkeever/passport-design#4]
The current spacing scale for this project is a bit old. So I have created a gist which has the newer spacing scale. You can change the spacing map to [this](https://gist.github.com/Anay-v2/16cca26fc8b7a75e3f550ea985cf195e).

**Comment by swkeever** [comment]
Thanks for the heads up. Updated in [this commit](https://github.com/swkeever/tailwind-scss/commit/75fc08ffc6c0aab75feab64d27c985eca08aeb19).
